import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'inventory',
        path: '',
        title: 'Inventory',
        translateKey: 'nav.inventory.title',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'inventory.products',
                path: '/products',
                title: 'Products',
                translateKey: 'nav.inventory.products',
                icon: 'inventoryProducts',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'inventory.categories',
                path: '/categories',
                title: 'Categories',
                translateKey: 'nav.inventory.categories',
                icon: 'inventoryCategories',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'inventory.stock',
                path: '/stock',
                title: 'Stock',
                translateKey: 'nav.inventory.stock',
                icon: 'inventoryStock',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'inventory.movements',
                path: '/movements',
                title: 'Movements',
                translateKey: 'nav.inventory.movements',
                icon: 'inventoryMovements',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'inventory.unitsOfMeasure',
                path: '/units-of-measure',
                title: 'Units of Measure',
                translateKey: 'nav.inventory.unitsOfMeasure',
                icon: 'inventoryUnitsOfMeasure',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'inventory.warehouses',
                path: '/warehouses',
                title: 'Warehouses',
                translateKey: 'nav.inventory.warehouses',
                icon: 'inventoryWarehouses',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'inventory.locations',
                path: '/locations',
                title: 'Locations',
                translateKey: 'nav.inventory.locations',
                icon: 'inventoryLocations',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'groupMenu.collapse',
                path: '',
                title: 'Group collapse menu',
                translateKey: 'nav.groupMenu.collapse.collapse',
                icon: 'groupCollapseMenu',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'groupMenu.collapse.item1',
                        path: '/group-collapse-menu-item-view-1',
                        title: 'Menu item 1',
                        translateKey: 'nav.groupMenu.collapse.item1',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'groupMenu.collapse.item2',
                        path: '/group-collapse-menu-item-view-2',
                        title: 'Menu item 2',
                        translateKey: 'nav.groupMenu.collapse.item2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
        ],
    },
    {
        key: 'sales',
        path: '',
        title: 'Sales',
        translateKey: 'nav.sales.title',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'sales.customers',
                path: '/customers',
                title: 'Customers',
                translateKey: 'nav.sales.customers',
                icon: 'salesCustomers',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
