import {
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_TITLE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'catalog',
        path: '',
        title: 'Catalog',
        translateKey: 'nav.catalog.title',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['product:read'],
        subMenu: [
            {
                key: 'catalog.categories',
                path: '/catalog/categories',
                title: 'Categories',
                translateKey: 'nav.catalog.categories',
                icon: 'catalogCategories',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['product:read'],
                subMenu: [],
            },
            {
                key: 'catalog.products',
                path: '/catalog/products',
                title: 'Products',
                translateKey: 'nav.catalog.products',
                icon: 'catalogProducts',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['product:read'],
                subMenu: [],
            },
            {
                key: 'catalog.unitsOfMeasure',
                path: '/catalog/units-of-measure',
                title: 'Units of Measure',
                translateKey: 'nav.catalog.unitsOfMeasure',
                icon: 'catalogUnitsOfMeasure',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['product:read'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'inventory',
        path: '',
        title: 'Inventory',
        translateKey: 'nav.inventory.title',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [
            'stock:read',
            'movement:write',
            'warehouse:write',
            'location:write',
            'lot:write',
            'serial:write',
            'adjustment:write',
            'transfer:write',
            'alert:read',
            'report:inventory:read',
        ],
        subMenu: [
            {
                key: 'inventory.stock',
                path: '/stock',
                title: 'Stock',
                translateKey: 'nav.inventory.stock',
                icon: 'inventoryStock',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['stock:read'],
                subMenu: [],
            },
            {
                key: 'inventory.movements',
                path: '/movements',
                title: 'Movements',
                translateKey: 'nav.inventory.movements',
                icon: 'inventoryMovements',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['movement:write'],
                subMenu: [],
            },
            {
                key: 'inventory.warehouses',
                path: '/warehouses',
                title: 'Warehouses',
                translateKey: 'nav.inventory.warehouses',
                icon: 'inventoryWarehouses',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['warehouse:write'],
                subMenu: [],
            },
            {
                key: 'inventory.locations',
                path: '/locations',
                title: 'Locations',
                translateKey: 'nav.inventory.locations',
                icon: 'inventoryLocations',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['location:write'],
                subMenu: [],
            },
            {
                key: 'inventory.lots',
                path: '/lots',
                title: 'Lots',
                translateKey: 'nav.inventory.lots',
                icon: 'inventoryLots',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['lot:write'],
                subMenu: [],
            },
            {
                key: 'inventory.serials',
                path: '/serials',
                title: 'Serial Numbers',
                translateKey: 'nav.inventory.serials',
                icon: 'inventorySerials',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['serial:write'],
                subMenu: [],
            },
            {
                key: 'inventory.adjustments',
                path: '/adjustments',
                title: 'Adjustments',
                translateKey: 'nav.inventory.adjustments',
                icon: 'inventoryAdjustments',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['adjustment:write'],
                subMenu: [],
            },
            {
                key: 'inventory.transfers',
                path: '/transfers',
                title: 'Transfers',
                translateKey: 'nav.inventory.transfers',
                icon: 'inventoryTransfers',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['transfer:write'],
                subMenu: [],
            },
            {
                key: 'inventory.alerts',
                path: '/alerts',
                title: 'Alerts',
                translateKey: 'nav.inventory.alerts',
                icon: 'inventoryAlerts',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['alert:read'],
                subMenu: [],
            },
            {
                key: 'inventory.reports',
                path: '/reports/inventory',
                title: 'Reports',
                translateKey: 'nav.inventory.reports',
                icon: 'inventoryReports',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['report:inventory:read'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'sales',
        path: '',
        title: 'Sales',
        translateKey: 'nav.sales.title',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['sale:read', 'customer:read'],
        subMenu: [
            {
                key: 'sales.customers',
                path: '/customers',
                title: 'Customers',
                translateKey: 'nav.sales.customers',
                icon: 'salesCustomers',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['customer:read'],
                subMenu: [],
            },
            {
                key: 'sales.sales',
                path: '/sales',
                title: 'Sales',
                translateKey: 'nav.sales.sales',
                icon: 'salesSales',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['sale:read'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'purchases',
        path: '',
        title: 'Purchases',
        translateKey: 'nav.purchases.title',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['purchase:read', 'supplier:read'],
        subMenu: [
            {
                key: 'purchases.suppliers',
                path: '/suppliers',
                title: 'Suppliers',
                translateKey: 'nav.purchases.suppliers',
                icon: 'purchasesSuppliers',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['supplier:read'],
                subMenu: [],
            },
            {
                key: 'purchases.purchaseOrders',
                path: '/purchase-orders',
                title: 'Purchase Orders',
                translateKey: 'nav.purchases.purchaseOrders',
                icon: 'purchasesPurchaseOrders',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['purchase:read'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'settings',
        path: '',
        title: 'Settings',
        translateKey: 'nav.settings.title',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'settings.users',
                path: '/settings/users',
                title: 'Usuarios',
                translateKey: 'nav.settings.users',
                icon: 'settingsUsers',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user:manage'],
                subMenu: [],
            },
            {
                key: 'settings.companyConfig',
                path: '/settings/company-config',
                title: 'Company Configuration',
                translateKey: 'nav.settings.companyConfig',
                icon: 'settingsCompanyConfig',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'settings.certificates',
                path: '/settings/certificates',
                title: 'Digital Certificates',
                translateKey: 'nav.settings.certificates',
                icon: 'settingsCertificates',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
